before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
archives:
- format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: instrumenta
    name: homebrew-instrumenta
  folder: Formula
  description: "Validate your Kubernetes configurations"
  homepage: "https://github.com/jenkins-x-plugins/kubeval"
  test: |
    system "#{bin}/kubeval --version"
scoop:
  bucket:
    owner: instrumenta
    name: scoop-instrumenta
  description: "Validate your Kubernetes configurations"
  homepage: "https://github.com/jenkins-x-plugins/kubeval"
